FILESEXTRAPATHS_append := "${THISDIR}:"
COMPATIBLE_MACHINE_zybo-zynq7    = "zybo-zynq7"
COMPATIBLE_MACHINE_ultra96v2     = "ultra96v2"
COMPATIBLE_MACHINE_fz3           = "fz3"
COMPATIBLE_MACHINE_zcu104-zynqmp = "zcu104-zynqmp"

FILES_${PN} += "files/*"
FILESEXTRAPATHS_append := "${THISDIR}/files/ultra96v2:"
SRC_URI_ultra96v2 = " file://psu_init_gpl.c"
SRC_URI_ultra96v2 += " file://psu_init_gpl.h"
